url: https://citycamp-website-template.citycamp.com # the base hostname & protocol for your site, e.g. http://example.com
title: "CityCamp" # the name of your site, e.g. ACME Corp.

# baseurl: "https://citycamp-website-template.citycamp.com" # when deploying to GitHub pages
baseurl: "" # when developing locally

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js

# CityCamp specific variables go below #########################################

city_camp_host_city: "Idealville"
city_camp_organizer_email: "example-organizer@citycamp.com"
# choose a tailwind color, and set it in .template-colors as well (near the top of index.html)
# see https://tailwindcss.com/docs/colors for more information on Tailwind colors
# then consider running https://webaim.org/resources/contrastchecker/ on the site
city_camp_dark_color: "gray-900"

# Display partners (sponsors) component or not
display_partners: true # true | false
partners:
  - name: "this"
    image_url: "https://citycamp.com/assets/img/posts/default-og.png"
  - name: "that"
    image_url: "https://citycamp.com/assets/img/posts/default-og.png"

social_links:
  - name: github
    url: https://github.com/CityCamp/citycamp-website-template
  - name: x
    url: https://x.com/citycamp
  - name: facebook
    url:
  - name: instagram
    url:
  - name: bluesky
    url:
  - name: youtube
    url:
