url: "" # the base hostname & protocol for your site, e.g. http://example.com
title: "CityCamp" # the name of your site, e.g. ACME Corp.

baseurl: "https://citycamp.github.io/citycamp-website-template" # when deploying to GitHub pages
# baseurl: "" # when developing locally

# CityCamp specific variables go here
city_camp_host_city: "Idealville"
city_camp_organizer_email: "example-organizer@citycamp.com"
city_camp_dark_color: "gray-900" # choose a tailwind color, and set it in .template-colors as well (near the top of index.html)

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js