url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "https://afomi.github.io/citycamp-template" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

# CityCamp specific variables go here
city_camp_host_city: "Idealville"
city_camp_organizer_email: "example-organizer@citycamp.com"

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js